/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    FormItemStep3: typeof import('./src/components/FormItemStep3.vue')['default']
    FormReview: typeof import('./src/components/FormReview.vue')['default']
    FormStep1: typeof import('./src/components/FormStep1.vue')['default']
    FormStep2: typeof import('./src/components/FormStep2.vue')['default']
    FormStep3: typeof import('./src/components/FormStep3.vue')['default']
    ProgressSteps: typeof import('./src/components/ProgressSteps.vue')['default']
    StepNavigation: typeof import('./src/components/StepNavigation.vue')['default']
  }
}
